services:
  mailpit:
    image: axllent/mailpit:v1.31
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    healthcheck:
      test: ["CMD", "/mailpit", "readyz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  redmine:
    image: redmine:5.1.3
    depends_on:
      db:
        condition: service_started
      mailpit:
        condition: service_healthy
    ports:
      - "8081:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: secret
    volumes:
      - ./files:/usr/src/redmine/files
      - ./redmine-config/configuration.yml:/usr/src/redmine/config/configuration.yml

  db:
    image: postgres:14
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: redmine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
